In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv("../data/processed/heart_processed.csv")

df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,1
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

In [5]:
df.shape

(303, 14)

In [7]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [9]:
X = df.drop("target", axis=1)

y = df["target"]

In [11]:
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0

In [13]:
y.head()

0    0
1    1
2    1
3    0
4    0
Name: target, dtype: int64

In [15]:
categorical_cols = ["cp", "restecg", "slope", "thal"]

for col in categorical_cols:
    print(f"{col}: {df[col].unique()}")

cp: [1. 4. 3. 2.]
restecg: [2. 0. 1.]
slope: [3. 2. 1.]
thal: [6. 3. 7.]

In [17]:
X_encoded = pd.get_dummies(
    X,
    columns=["cp", "restecg", "slope", "thal"],
    drop_first=True,
    dtype=int
)

In [19]:
X_encoded.head()

,age,sex,trestbps,chol,fbs,thalach,exang,oldpeak,ca,cp_2.0,cp_3.0,cp_4.0,restecg_1.0,restecg_2.0,slope_2.0,slope_3.0,thal_6.0,thal_7.0
0,63.0,1.0,145.0,233.0,1.0,150.0,0.0,2.3,0.0,0,0,0,0,1,0,1,1,0
1,67.0,1.0,160.0,286.0,0.0,108.0,1.0,1.5,3.0,0,0,1,0,1,1,0,0,0
2,67.0,1.0,120.0,229.0,0.0,129.0,1.0,2.6,2.0,0,0,1,0,1,1,0,0,1
3,37.0,1.0,130.0,250.0,0.0,187.0,0.0,3.5,0.0,0,1,0,0,0,0,1,0,0
4,41.0,0.0,130.0,204.0,0.0,172.0,0.0,1.4,0.0,1,0,0,0,1,0,0,0,0

In [21]:
X_encoded.shape

(303, 18)

In [23]:
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [25]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (242, 18)
X_test : (61, 18)
y_train: (242,)
y_test : (61,)

In [27]:
print(y_train.value_counts())

print()

print(y_test.value_counts())

target
0    131
1    111
Name: count, dtype: int64

target
0    33
1    28
Name: count, dtype: int64

In [29]:
from sklearn.preprocessing import StandardScaler

In [31]:
scaler = StandardScaler()

In [33]:
X_train_scaled = scaler.fit_transform(X_train)

In [37]:
X_test_scaled = scaler.transform(X_test)

In [39]:
print(X_train_scaled.shape)
print(X_test_scaled.shape)

(242, 18)
(61, 18)

In [41]:
X_train_scaled[:5]

array([[-0.72948484,  0.68313005, -0.39569185,  0.4581394 , -0.41119597,
         0.70837124, -0.69617712, -0.44544493, -0.68971531, -0.45825757,
        -0.59962535,  1.03362279, -0.06441566,  1.02510851,  1.09544512,
        -0.26607604, -0.21821789,  1.24393264],
       [ 0.05016647,  0.68313005, -0.05451337,  0.23059762, -0.41119597,
         0.22249537, -0.69617712, -0.89162735, -0.68971531,  2.1821789 ,
        -0.59962535, -0.96747093, -0.06441566, -0.97550649, -0.91287093,
        -0.26607604, -0.21821789, -0.80390205],
       [-0.06121229, -1.46385011,  0.0592128 ,  0.72360482,  2.43193045,
         0.3991775 ,  1.43641607, -0.89162735,  0.44573438,  2.1821789 ,
        -0.59962535, -0.96747093, -0.06441566,  1.02510851, -0.91287093,
        -0.26607604, -0.21821789, -0.80390205],
       [-0.06121229,  0.68313005, -1.30550115,  1.12180294, -0.41119597,
         0.26666591, -0.69617712, -0.89162735, -0.68971531,  2.1821789 ,
        -0.59962535, -0.96747093, -0.06441566, -0.97550649, -0.91287093,
        -0.26607604, -0.21821789,  1.24393264],
       [ 0.27292398, -1.46385011,  0.51411744, -0.16760051, -0.41119597,
        -1.19096169,  1.43641607, -0.71315438, -0.68971531, -0.45825757,
        -0.59962535,  1.03362279, -0.06441566, -0.97550649,  1.09544512,
        -0.26607604, -0.21821789,  1.24393264]])

In [43]:
import joblib

joblib.dump(scaler, "../artifacts/scaler.pkl")

['../artifacts/scaler.pkl']